DROP SCHEMA IF EXISTS RESTAURANT ;
CREATE SCHEMA RESTAURANT;

USE RESTAURANT;

CREATE TABLE DISHES
	(
		DISH_CODE VARCHAR(3) PRIMARY KEY,
        DISH_NAME VARCHAR(60) NOT NULL,
        DISH_TYPE VARCHAR (20) NOT NULL,				-- ANTIPASTO, PRIMO, SECONDO, DOLCE, BEVANDA
		DISH_PRICE DOUBLE NOT NULL,
        VEGAN BOOLEAN DEFAULT FALSE,					-- TRUE SE IL PIATTO E' PER VEGANI
        VEGETARIAN BOOLEAN DEFAULT FALSE,					-- TRUE SE IL PIATTO E' PER VEGETARIANI
        CELIAC BOOLEAN DEFAULT FALSE					-- TRUE SE IL PIATTO E' PER CELIACI
     );
     
-- INSERIMENTO ANTIPASTI
INSERT INTO DISHES VALUES('A01', 'TAGLIERE SALUMI MISTI', 'STARTER', 5, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES('A02', 'TARTARE DI SALMONE', 'STARTER', 15, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES('A03', 'GNOCCO FRITTO', 'STARTER', 5, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A04', 'VERDURE GRIGLIATE', 'STARTER', 4, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A05', 'BRUSCHETTA CON POMODORINI', 'STARTER', 2, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A06', 'TORTA SALATA', 'STARTER', 3, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A07', 'TAGLIERE FORMAGGI MISTI', 'STARTER', 5, FALSE, TRUE, TRUE);
INSERT INTO DISHES VALUES('A08', 'MOZZARELLA IN CARROZZA', 'STARTER', 3, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A09', 'COZZE GRATINATE', 'STARTER', 7.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A10', 'TOFU CON SALSA DI SOIA', 'STARTER', 3.5, TRUE, TRUE, FALSE);

-- INSERIMENTO PRIMI
INSERT INTO DISHES VALUES('P01', 'PAELLA','FIRST_COURSE', 12.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P02', 'SPAGHETTI ALLO SCOGLIO','FIRST_COURSE', 10, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P03', 'CARBONARA','FIRST_COURSE', 8, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P04', 'LASAGNA','FIRST_COURSE', 7.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P05', 'RISOTTO AI FUNGHI','FIRST_COURSE', 7, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES('P06', 'PASTA E CECI','FIRST_COURSE', 5 , TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES('P07', 'RAVIOLI BURRO E SALVIA','FIRST_COURSE', 5.5 , FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES('P08', 'SPAGHETTI DI SOIA CON GAMBERI','FIRST_COURSE', 7.5 , FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES('P09', 'GNOCCHI DI PATATE AL SUGO','FIRST_COURSE', 6 , TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES('P10', 'FUSILLI SENZA GLUTINE CON PESTO DI CAVOLFIORE','FIRST_COURSE', 7.5 , TRUE, TRUE, TRUE);

-- INSERIMENTO SECONDI
INSERT INTO DISHES VALUES ('S01','ARAGOSTA ALLA CATALANA','MAIN_COURSE', 18.5, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES ('S02','COTOLETTA ALLA MILANESE CON PATATE','MAIN_COURSE', 10, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES ('S03','INSALATONA MISTA','MAIN_COURSE', 5, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('S04','SCALOPPINE AL LIMONE','MAIN_COURSE', 8.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES ('S05','SEPPIE CON PISELLI','MAIN_COURSE', 10.5, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES ('S06','SEITAN ALLA PIZZAIOLA','MAIN_COURSE', 9.5, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('S07','POLLO AL CURRY','MAIN_COURSE', 8, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES ('S08','FRITTO MISTO DI PESCE','MAIN_COURSE', 15, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES ('S09','OMELETTE DI VERDURE','MAIN_COURSE', 6.5, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('S10','GRIGLIATA MISTA','MAIN_COURSE', 13, FALSE, FALSE, FALSE);


-- INSERIMENTO DESSERT
INSERT INTO DISHES VALUES ('D01', 'CHEESECAKE','DESSERT', 4, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('D02', 'TIRAMISU','DESSERT', 5, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('D03', 'SORBETTO AL LIMONE','DESSERT', 3.5, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('D04', 'CROSTATA DI FRAGOLE','DESSERT', 4.5, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('D05', 'TORTA CON FARINA SARACENA','DESSERT', 5, FALSE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('D06', 'GELATO AL CIOCCOLATO','DESSERT', 3.5, TRUE, TRUE, TRUE);

-- INSERIMENTO BEVANDE
INSERT INTO DISHES VALUES ('B01', 'ACQUA MINERALE NATURALE 1L','DRINK', 2, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B02', 'ACQUA MINERALE FRIZZANTE 1L','DRINK', 2, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B03', 'COCA COLA IN LATTINA','DRINK', 2.5, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B04', 'ARANCIATA IN LATTINA','DRINK', 2.5, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B05', 'GASSOSA IN LATTINA','DRINK', 2.5, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B06', 'BIRRA MEDIA CHIARA','DRINK', 4.5, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('B07', 'BIRRA MEDIA SCURA','DRINK', 4.5, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES ('B08', 'VINO ROSSO DELLA CASA MEZZO LITRO','DRINK', 7, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B09', 'VINO BIANCO DELLA CASA MEZZO LITRO','DRINK', 7, TRUE, TRUE, TRUE);
INSERT INTO DISHES VALUES ('B10', 'PROSECCO','DRINK', 8, TRUE, TRUE, TRUE);

  

CREATE TABLE ALLERGENS
	(
		ALLERGEN_CODE CHAR PRIMARY KEY,
        ALLERGEN_DESCR VARCHAR(50) NOT NULL
        
    );

-- INSERIMENTO ALLERGENI
INSERT INTO ALLERGENS VALUES ('A', 'GLUTINE');
INSERT INTO ALLERGENS VALUES ('B', 'CROSTACEI E DERIVATI');
INSERT INTO ALLERGENS VALUES ('C', 'UOVA E DERIVATI');
INSERT INTO ALLERGENS VALUES ('D', 'PESCE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('E', 'ARACHIDI E DERIVATI');
INSERT INTO ALLERGENS VALUES ('F', 'SOIA E DERIVATI');
INSERT INTO ALLERGENS VALUES ('G', 'LATTE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('H', 'FRUTTA A GUSCIO');
INSERT INTO ALLERGENS VALUES ('I', 'SEDANO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('L', 'SENAPE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('M', 'SEMI DI SESAMO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('N', 'ANIDRIDE SOLVOROSA E SOLFITI');
INSERT INTO ALLERGENS VALUES ('O', 'LUPINO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('P', 'MOLLUSCHI E DERIVATI');
    

CREATE TABLE INGREDIENTS
	(
		INGREDIENT_CODE VARCHAR(4) PRIMARY KEY,
        INGREDIENT_NAME VARCHAR(50) NOT NULL
		
    );
INSERT INTO INGREDIENTS VALUES ('I01','CURCUMA');
INSERT INTO INGREDIENTS VALUES ('I02','CURRY');
    

    
CREATE TABLE ALLERGENS_IN_DISHES
	(
		ALLERGEN_CODE CHAR,
        DISH_CODE VARCHAR(3),
		PRIMARY KEY(ALLERGEN_CODE, DISH_CODE),
        FOREIGN KEY (DISH_CODE) REFERENCES DISHES(DISH_CODE),
		FOREIGN KEY (ALLERGEN_CODE) REFERENCES ALLERGENS(ALLERGEN_CODE)
		
    );
    
INSERT INTO ALLERGENS_IN_DISHES VALUES ('A','A01');
INSERT INTO ALLERGENS_IN_DISHES VALUES ('B','A01');
INSERT INTO ALLERGENS_IN_DISHES VALUES ('C','A01');

CREATE TABLE INGREDIENTS_IN_DISHES
	(
		INGREDIENT_CODE VARCHAR(4),
        DISH_CODE VARCHAR(3),
        PRIMARY KEY (INGREDIENT_CODE, DISH_CODE),
        FOREIGN KEY (DISH_CODE) REFERENCES DISHES(DISH_CODE),
		FOREIGN KEY (INGREDIENT_CODE) REFERENCES INGREDIENTS(INGREDIENT_CODE)
        
    );
    
INSERT INTO INGREDIENTS_IN_DISHES VALUES('I01','A01');
INSERT INTO INGREDIENTS_IN_DISHES VALUES('I02','A01');
    
    
CREATE TABLE RESERVATIONS
	(
		RES_CODE VARCHAR(4) PRIMARY KEY,
		N_GUESTS INT NOT NULL,
		RES_COST DOUBLE NOT NULL,
		EVENT_DATE VARCHAR(50) NOT NULL,
		CUSTOMER_NAME_SURNAME VARCHAR(50) NOT NULL,
		CUSTOMER_EMAIL VARCHAR(50) NOT NULL
	);


    