DROP SCHEMA IF EXISTS RESTAURANT ;
CREATE SCHEMA RESTAURANT;

USE RESTAURANT;

CREATE TABLE DISHES
	(
		DISH_CODE VARCHAR(3) PRIMARY KEY,
        DISH_NAME VARCHAR(60) NOT NULL,
        DISH_TYPE VARCHAR (20) NOT NULL,				-- ANTIPASTO, PRIMO, SECONDO, DOLCE, BEVANDA
		DISH_PRICE DOUBLE NOT NULL,
        VEGAN BOOLEAN DEFAULT FALSE,					-- TRUE SE IL PIATTO E' PER VEGANI
        VEGETARIAN BOOLEAN DEFAULT FALSE,					-- TRUE SE IL PIATTO E' PER VEGETARIANI
        CELIAC BOOLEAN DEFAULT FALSE					-- TRUE SE IL PIATTO E' PER CELIACI
     );
     
-- INSERIMENTO ANTIPASTI
INSERT INTO DISHES VALUES('A01', 'TAGLIERE SALUMI MISTI', 'STARTER', 5, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES('A02', 'TARTARE DI SALMONE', 'STARTER', 15, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A03', 'GNOCCO FRITTO', 'STARTER', 5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A04', 'VERDURE FRITTE', 'STARTER', 4, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A05', 'BRUSCHETTA CON POMODORINI', 'STARTER', 2, TRUE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A06', 'TORTA SALATA', 'STARTER', 3, TRUE, FALSE, FALSE);
INSERT INTO DISHES VALUES('A07', 'TAGLIERE FORMAGGI MISTI', 'STARTER', 5, FALSE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A08', 'MOZZARELLA IN CARROZZA', 'STARTER', 3, FALSE, FALSE, TRUE);
INSERT INTO DISHES VALUES('A09', 'COZZE GRATINATE', 'STARTER', 7.5, TRUE, TRUE, FALSE);
INSERT INTO DISHES VALUES('A10', 'OLIVE ASCOLANE', 'STARTER', 3, FALSE, FALSE, FALSE);
-- INSERIMENTO PRIMI
INSERT INTO DISHES VALUES('P01', 'PAELLA','FIRST_COURSE', 12.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P02', 'SPAGHETTI ALLO SCOGLIO','FIRST_COURSE', 10, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P03', 'CARBONARA','FIRST_COURSE', 8, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P04', 'LASAGNA','FIRST_COURSE', 7.5, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P05', 'RISOTTO E FUNGHI','FIRST_COURSE', 7, FALSE, FALSE, FALSE);
INSERT INTO DISHES VALUES('P06', 'CASSOEULA','FIRST_COURSE', 6 , FALSE, FALSE, FALSE);
-- INSERIMENTO SECONDI
INSERT INTO DISHES VALUES ('S01','ARAGOSTA','MAIN_COURSE', 20, FALSE, FALSE, TRUE);
-- INSERIMENTO DESSERT
INSERT INTO DISHES VALUES ('D01', 'CHEESECAKE','DESSERT', 5, FALSE, FALSE, FALSE);
-- INSERIMENTO BEVANDE
INSERT INTO DISHES VALUES ('B01', 'ACQUA MINERALE NATURALE 1L','DRINK', 2, FALSE, FALSE, FALSE);

  

CREATE TABLE ALLERGENS
	(
		ALLERGEN_CODE CHAR PRIMARY KEY,
        ALLERGEN_DESCR VARCHAR(50) NOT NULL
        
    );

-- INSERIMENTO ALLERGENI
INSERT INTO ALLERGENS VALUES ('A', 'GLUTINE');
INSERT INTO ALLERGENS VALUES ('B', 'CROSTACEI E DERIVATI');
INSERT INTO ALLERGENS VALUES ('C', 'UOVA E DERIVATI');
INSERT INTO ALLERGENS VALUES ('D', 'PESCE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('E', 'ARACHIDI E DERIVATI');
INSERT INTO ALLERGENS VALUES ('F', 'SOIA E DERIVATI');
INSERT INTO ALLERGENS VALUES ('G', 'LATTE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('H', 'FRUTTA A GUSCIO');
INSERT INTO ALLERGENS VALUES ('I', 'SEDANO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('L', 'SENAPE E DERIVATI');
INSERT INTO ALLERGENS VALUES ('M', 'SEMI DI SESAMO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('N', 'ANIDRIDE SOLVOROSA E SOLFITI');
INSERT INTO ALLERGENS VALUES ('O', 'LUPINO E DERIVATI');
INSERT INTO ALLERGENS VALUES ('P', 'MOLLUSCHI E DERIVATI');
    

CREATE TABLE INGREDIENTS
	(
		INGREDIENT_CODE VARCHAR(3) PRIMARY KEY,
        INGREDIENT_NAME VARCHAR(50) NOT NULL
		
    );

    

    
CREATE TABLE ALLERGENS_IN_DISHES
	(
		ALLERGEN_CODE CHAR,
        DISH_CODE VARCHAR(3),
		PRIMARY KEY(ALLERGEN_CODE, DISH_CODE),
        FOREIGN KEY (DISH_CODE) REFERENCES DISHES(DISH_CODE),
		FOREIGN KEY (ALLERGEN_CODE) REFERENCES ALLERGENS(ALLERGEN_CODE)
		
    );
    
INSERT INTO ALLERGENS_IN_DISHES VALUES ('A','A01');

CREATE TABLE INGREDIENTS_IN_DISHES
	(
		INGREDIENT_CODE VARCHAR(3),
        DISH_CODE VARCHAR(3),
        PRIMARY KEY (INGREDIENT_CODE, DISH_CODE),
        FOREIGN KEY (DISH_CODE) REFERENCES DISHES(DISH_CODE),
		FOREIGN KEY (INGREDIENT_CODE) REFERENCES INGREDIENTS(INGREDIENT_CODE)
        
    );
    

    

CREATE VIEW STARTERS AS(

	SELECT DISH_CODE, DISH_NAME, DISH_TYPE, DISH_PRICE,  CASE 
                  WHEN VEGAN = TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGAN, 
             CASE 
                  WHEN VEGETARIAN=TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGETARIAN, 
             CASE 
                  WHEN CELIAC=TRUE
                     THEN 'YES'
                  ELSE 'NO' 
             END  as CELIAC
    FROM DISHES
    WHERE DISH_TYPE='STARTER'

);
CREATE VIEW FIRST_COURSES AS(

	SELECT DISH_CODE, DISH_NAME, DISH_TYPE, DISH_PRICE,  CASE 
                  WHEN VEGAN = TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGAN, 
             CASE 
                  WHEN VEGETARIAN=TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGETARIAN, 
             CASE 
                  WHEN CELIAC=TRUE
                     THEN 'YES'
                  ELSE 'NO' 
             END  as CELIAC
    FROM DISHES
    WHERE DISH_TYPE='FIRST_COURSE'
);



CREATE VIEW MAIN_COURSES AS(

	SELECT DISH_CODE, DISH_NAME, DISH_TYPE, DISH_PRICE,  CASE 
                  WHEN VEGAN = TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGAN, 
             CASE 
                  WHEN VEGETARIAN=TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGETARIAN, 
             CASE 
                  WHEN CELIAC=TRUE
                     THEN 'YES'
                  ELSE 'NO' 
             END  as CELIAC
    FROM DISHES
    WHERE DISH_TYPE='MAIN_COURSE'
);
CREATE VIEW DESSERTS AS(

	SELECT DISH_CODE, DISH_NAME, DISH_TYPE, DISH_PRICE,  CASE 
                  WHEN VEGAN = TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGAN, 
             CASE 
                  WHEN VEGETARIAN=TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGETARIAN, 
             CASE 
                  WHEN CELIAC=TRUE
                     THEN 'YES'
                  ELSE 'NO' 
             END  as CELIAC
    FROM DISHES
    WHERE DISH_TYPE='DESSERT'
);

CREATE VIEW DRINKS AS(

	SELECT DISH_CODE, DISH_NAME, DISH_TYPE, DISH_PRICE,  CASE 
                  WHEN VEGAN = TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGAN, 
             CASE 
                  WHEN VEGETARIAN=TRUE 
                     THEN 'YES' 
                  ELSE 'NO'
             END  as VEGETARIAN, 
             CASE 
                  WHEN CELIAC=TRUE
                     THEN 'YES'
                  ELSE 'NO' 
             END  as CELIAC
    FROM DISHES
    WHERE DISH_TYPE='DRINK'
);




